<?php
/**
 * PSR-4 Autoloader
 *
 * @package WPDTRT_Plugin
 * @version 1.4.15
 * @see     http://phpenthusiast.com/blog/how-to-autoload-with-composer
 */

/**
 * Autoload PHP classes.
 *  autoload.php is generated by Composer and autoloads classes for all vendors.
 *  $project_root_path allows for child plugins, where this PHP file is nested within vendor/.
 *
 * @see https://www.php-fig.org/psr/psr-4/
 * @see https://stackoverflow.com/a/37952183/6850747
 * @todo https://github.com/dotherightthing/wpdtrt-plugin/issues/124
 */
if ( defined( 'WPDTRT_PLUGIN_CHILD' ) ) {
	$project_root_path = realpath( __DIR__ . '/../../..' ) . '/';
} else {
	$project_root_path = '';
}

require_once $project_root_path . 'vendor/autoload.php';
